[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icecream = "0.1.0"
png = "0.17.10"